### ISSUE TITLE
How to build it using visual studio code?

### ISSUE THREAD

**Issue by sword134** [pierotofy/PokerMuck#3]
Hello,
I am used to python programming and have no experience with C#. I am trying to build it in VS Code but I get the following error:
error MSB3822: Non-string resources require the System.Resources.Extensions assembly at runtime, but it was not found in this project's references.

**Comment by pierotofy** [comment]
Hey @sword134 :hand: this project was created before Visual Studio Code was around; I'd recommend to build it using Visual Studio Community Edition.

**Comment by sword134** [comment]
@pierotofy thats a shame. Visual Studio xxxx always take up so much space. Is there any chance you have a compiled version laying around anywhere?

**Comment by pierotofy** [comment]
I do not, sorry!

**Comment by sword134** [comment]
> I do not, sorry!

@pierotofy i've successfully built the application and it runs with the debug window etc. However there is no hud and it keeps printing the same message about "Is this the first hand?". I've set the hands directory to the correct one as well and I can also take a screenshot of the application with the screenshot button. The HUD is just missing.

Debug message in question:

A valid window title was found (Session: 00:18 - Gemma - 50/100 Play Money - No Limit Hold'em - Logged In as XXXXX) but no filename associated with the window could be found using pattern HH[0-9]+  Gemma . Is this our first hand at the table and no hand history is available?
Window title: PokerMuck

**Comment by pierotofy** [comment]
It could be a bug, due to changes in the poker client since I've last updated this.

I currently don't have the time to fix this myself, but I'd welcome a pull request to fix it. :pray:

**Comment by sword134** [comment]
@pierotofy I program in Python and have no experience with C# or C++. Oh well.
